# .github/workflows/run-azure-login.yml
name: Run Azure Login with OpenID Connect

on: [push]

permissions:
  id-token: write # Require write permission to Fetch an OIDC token.
      
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Deployment Prerequisites
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module Az, Microsoft.Graph -AllowClobber -Force

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
          enable-AzPSSession: true

      - name: Checkout Azure IPAM Code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            deploy
            engine
            ui  

      - name: Deploy Azure IPAM
        working-directory: deploy
        id: deployScript
        shell: pwsh
        run: ./deploy.ps1 -Location "uksouth" -ParameterFile "main.parameters.bicep.json" -Debug
    
